[options]
admin_passwd = admin
db_host = db
db_port = 5432
db_user = odoo
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons,/mnt/wpmoo-addons
data_dir = /var/lib/odoo
http_port = 8069
gevent_port = 8072
proxy_mode = False
logfile = /var/lib/odoo/odoo-server.log
log_level = info
server_wide_modules = base,web
